Category.destroy_all
Recipe.destroy_all
Review.destroy_all

cakes = Category.create(name:"cakes")
cupcakes = Category.create(name:"cupcakes")
cookies = Category.create(name:"cookies")
other = Category.create(name:"other")


Recipe.create(name: "Peanut Butter Mug Cake", category_id: cakes.id , ingredients: "3 tbsp peanut butter, 1tbsp + 1tsp white granulated sugar, 1 large egg", procedure: "Whisk all ingredients into an oversized, microwave-safe mug until batter is smooth and egg is fully whisked in. Microwave for about 1 minute. Let cake cool a few minutes before eating." , picture: "https://lh3.googleusercontent.com/-RiiwPS9S8GM/VvYj5Pqhz9I/AAAAAAAFSqs/2NYy8cViIwg9PsOHTcmp7tC6SJUYBkxtgCCo/s800-Ic42/3-ingredient-flourless-peanut-butter-mug-cake-20%2B%25281%2529.jpg")
Recipe.create(name: "Flourless Peanut Butter Cookies", category_id: cookies.id , ingredients: "1 cup peanut butter, 1/4 cup granulated sugar, 1 egg", procedure: "Mix all the ingredients. Make tablespoon sized balls with the mixture and place on a prepared baking sheet, 2 inches apart. Bake for 12-14 minutes, until the cookies are slightly dark at the bottom.", picture: "https://images.britcdn.com/wp-content/uploads/2016/12/3-Ingredient-Peanut-Butter-cookies-are-so-easy-to-make1-e1448370551240-645x968.jpg?w=1000&auto=format&q=50")
Recipe.create(name: "Shortbread cookies", category_id: cookies.id , ingredients: "2 cups salted butter (cold and cut into pieces), 1 cup packed light brown sugar, 4 1/2 cups all purpose flour, divided", procedure: "Preheat oven to 325F. Line baking sheets with parchment paper. In the bowl of a stand mixer, add butter and brown sugar. Using paddle attachment on medium-high speed, mix until fluffy and light, several minutes. Add only 3 1/2 cups of the flour and mix on medium-low speed until combined. On a large board, sprinkle 1/2 cup flour to keep dough from sticking to the board. Use rubber spatula to transfer dough to the board. Knead dough by hand for 5 minutes, adding only as much of the remaining 1/2 cup flour as needed to make a soft dough, while continuing to knead by hand. The dough should end up soft and pliable, similar to play-dough, not sticky. Work in desired amount of sprinkles, if using. (Important Note: You may not end up using all the flour, depending on how your dough feels; it’s important to stop adding flour as soon as your dough feels like soft play dough.) Divide dough into thirds, wrap tightly, and chill for at least 30 minutes or until firm enough to roll and cut shapes. Roll one-third of the dough out to about 1/2 inch thickness (lightly flour board if needed.) Either cut into 3×1 rectangular strips, triangles, or use cookie cutter for shapes. Place each cookie 2 inches apart on baking sheet. Poke cookies with fork to design if not using sprinkles. Bake 15-20 minutes, or until edges are golden brown. If your shapes are smaller, bake less time. Bake longer for bigger shapes. Repeat with the remaining dough, working in batches so dough stays chilled and workable. Cool completely on wire rack before serving. Cookies keep very when sealed airtight, at room temp.", picture: "https://images.britcdn.com/wp-content/uploads/2016/12/3-ingred.-shortbread-cookies-645x874.jpg?w=1000&auto=format&q=50")
Recipe.create(name: "Peanut Butter Fudge", category_id: other.id , ingredients:"1 can (14.5 oz) sweetened condensed milk (not evaporated), 2/3 cup peanut butter (traditional style like Jif brand, not natural), 1 package (16 oz) white almond bark , broken into pieces", procedure: "Line 8-inch square pan with foil that overhangs all four edges and spray with cooking spray. If using a 6x2-inch holiday tin as I did, lightly spray it with cooking spray and set aside. Place the sweetened condensed milk (not evaporated milk), 2/3 cup creamy peanut butter and almond bark in a large microwavable bowl. Heat in the microwave uncovered on high (100% power) in 1-minute increments, stirring well between each, until melted and smooth. This will take about 3 minutes. Be careful; the bowl may get hot. Immediately pour the mixture into the prepared pan or tin. Pick up and drop the pan twice or until the surface becomes level. Transfer to the refrigerator and let chill until set, about 2 hours. Sprinkle with sea salt, if using.", picture: "https://images.britcdn.com/wp-content/uploads/2016/12/3-minute-3-ingredient-peanut-butter-fudge-645x739.png?w=1000&auto=format&q=50")
Recipe.create(name: "Rolo Pretzel Turtles", category_id: other.id , ingredients: "pretzels, rolo candies, pecan halves", procedure: "Preheat oven to 350 degrees. Line a baking sheet with parchment paper. Arrange desired number of pretzels on baking sheet. Place one Rolo candy in the center of each pretzel. Bake for 4-5 minutes. Remove from oven and immediately top each warm Rolo with a pecan half. Allow to cool thoroughly. Store in a sealed container." , picture: "https://www.garnishwithlemon.com/wp-content/uploads/2014/11/Rolo-Pretzel-Truffles-2-of-2.jpg")
Recipe.create(name: "Nutella Mini Cupcakes", category_id: cupcakes.id, ingredients: "1 cup Nutella (divided), 1 large egg, 5 Tbsp all purpose flour", procedure: "Heat oven to 350. Line 9-10 cups of a mini muffin pan with liners (or about 5 reg size if you don't have a mini pan). Mix together 1/2 cup of the Nutella & egg & whisk until smooth. Add flour and whisk until well blended. Spoon batter into the muffin cups & bake until toothpick comes out pretty clean (about 11 to 12 minutes). Let cool. Warm remaining Nutella 15-20 seconds in microwave  until warm & soft. Dip tops of cupcakes into the Nutella & sprinkle with salt if desired.", picture: "https://www.sixsistersstuff.com/wp-content/uploads/2013/09/Nutella-683x1024.jpg")
# Recipe.create(name:, category_id: , ingredients:, procedure: , picture:)
# Recipe.create(name:, category_id: , ingredients:, procedure: , picture:)
# Recipe.create(name:, category_id: , ingredients:, procedure: , picture:)
# Recipe.create(name:, category_id: , ingredients:, procedure: , picture:)
# Recipe.create(name:, category_id: , ingredients:, procedure: , picture:)
# Recipe.create(name:, category_id: , ingredients:, procedure: , picture:)
# Recipe.create(name:, category_id: , ingredients:, procedure: , picture:)
# Recipe.create(name:, category_id: , ingredients:, procedure: , picture:)


Review.create(recipe_id: 53, content:"yuuuummm!")
Review.create(recipe_id: 52, content:"best cookies ever")
Review.create(recipe_id: 57, content:"hmmm not great")
Review.create(recipe_id: 54, content:"too sweet!")
Review.create(recipe_id: 55, content:"perfect!!")
Review.create(recipe_id: 56, content:"great dessert")